builders:
  dart_mapper_clean|mapperBuilder:
    import: "package:dart_mapper_clean/builder.dart"
    builder_factories: ["mapperBuilder"]
    build_extensions: {".dart": [".mapper.dart"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      dart_mapper_clean|mapperBuilder:
        enabled: true
        generate_for:
          include:
            - lib/**  # حتماً مطمئن شو فایل‌های lib داری


