builders:
  mapper|mapperBuilder:
    import: "package:dart_mapper_clean/src/mapper_generator.dart"
    builder_factories: ["mapperBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
